CREATE TABLE IF NOT EXISTS "users" (
  -- primary key
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- table fields
  "username" VARCHAR(20) NOT NULL,
  "email" VARCHAR(50) NOT NULL,
  "password_hash" VARCHAR NOT NULL,
  "full_name" varchar(100),
  "avatar_url" VARCHAR,
  "is_email_verified" BOOLEAN DEFAULT false NOT NULL,
  "last_sign_in_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  -- common fields
  "entity_id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "updated_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "is_deleted" BOOLEAN DEFAULT false NOT NULL
  -- constraints
);

CREATE TABLE IF NOT EXISTS "refresh_tokens" (
  -- primary key
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- table fiedls
  "user_id" INTEGER NOT NULL,
  "token" VARCHAR NOT NULL,
  "is_revoked" BOOLEAN DEFAULT false NOT NULL,
  "expires_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "replaced_by_token" VARCHAR,
  -- commnon fields
  "entity_id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "updated_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "is_deleted" BOOLEAN DEFAULT false NOT NULL,
  -- constraints
  CONSTRAINT "fk_refresh_token_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "conversations" (
  -- primary key
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- table fields
  "type" VARCHAR(20) DEFAULT 'direct' NOT NULL,
  "last_message_id" INTEGER,
  "last_message_at" TIMESTAMPTZ,
  -- common fields
  "entity_id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "updated_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "is_deleted" BOOLEAN DEFAULT false NOT NULL,
  -- constraints
  CONSTRAINT "ck_conversations_type" CHECK ("type" = 'direct')
);

CREATE UNIQUE INDEX IF NOT EXISTS "ux_conversations_entity_id"
  ON "conversations" ("entity_id");

CREATE INDEX IF NOT EXISTS "ix_conversations_last_message_at"
  ON "conversations" ("last_message_at" DESC);

CREATE TABLE IF NOT EXISTS "conversation_members" (
  -- primary key
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- table fields
  "conversation_id" INTEGER NOT NULL,
  "user_id" INTEGER NOT NULL,
  "last_read_message_id" INTEGER,
  "last_read_at" TIMESTAMPTZ,
  -- common fields
  "entity_id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "updated_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "is_deleted" BOOLEAN DEFAULT false NOT NULL,
  -- constraints
  CONSTRAINT "fk_conversation_members_conversations_conversation_id" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE CASCADE,
  CONSTRAINT "fk_conversation_members_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "ux_conversation_members_conversation_id_user_id"
  ON "conversation_members" ("conversation_id", "user_id")
  WHERE "is_deleted" = false;

CREATE INDEX IF NOT EXISTS "ix_conversation_members_user_id"
  ON "conversation_members" ("user_id");

CREATE INDEX IF NOT EXISTS "ix_conversation_members_conversation_id"
  ON "conversation_members" ("conversation_id");

CREATE TABLE IF NOT EXISTS "direct_conversations" (
  -- primary key
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- table fields
  "conversation_id" INTEGER NOT NULL,
  "user_low_id" INTEGER NOT NULL,
  "user_high_id" INTEGER NOT NULL,
  -- common fields
  "entity_id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "updated_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "is_deleted" BOOLEAN DEFAULT false NOT NULL,
  -- constraints
  CONSTRAINT "fk_direct_conversations_conversations_conversation_id" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE CASCADE,
  CONSTRAINT "fk_direct_conversations_users_user_low_id" FOREIGN KEY ("user_low_id") REFERENCES "users"("id") ON DELETE CASCADE,
  CONSTRAINT "fk_direct_conversations_users_user_high_id" FOREIGN KEY ("user_high_id") REFERENCES "users"("id") ON DELETE CASCADE,
  CONSTRAINT "ck_direct_conversations_different_users" CHECK ("user_low_id" < "user_high_id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "ux_direct_conversations_user_pair"
  ON "direct_conversations" ("user_low_id", "user_high_id")
  WHERE "is_deleted" = false;

CREATE UNIQUE INDEX IF NOT EXISTS "ux_direct_conversations_conversation_id"
  ON "direct_conversations" ("conversation_id")
  WHERE "is_deleted" = false;

CREATE TABLE IF NOT EXISTS "messages" (
  -- primary key
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- table fields
  "conversation_id" INTEGER NOT NULL,
  "sender_user_id" INTEGER NOT NULL,
  "content" VARCHAR(4000),
  "sent_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  -- common fields
  "entity_id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "updated_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "is_deleted" BOOLEAN DEFAULT false NOT NULL,
  -- constraints
  CONSTRAINT "fk_messages_conversations_conversation_id" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE CASCADE,
  CONSTRAINT "fk_messages_users_sender_user_id" FOREIGN KEY ("sender_user_id") REFERENCES "users"("id") ON DELETE CASCADE,
  CONSTRAINT "ck_messages_content_not_empty" CHECK ("content" IS NULL OR length(trim("content")) > 0)
);

-- Existing databases originally required every message to contain text.
ALTER TABLE "messages"
  ALTER COLUMN "content" DROP NOT NULL;

ALTER TABLE "messages"
  DROP CONSTRAINT IF EXISTS "ck_messages_content_not_empty";

ALTER TABLE "messages"
  ADD CONSTRAINT "ck_messages_content_not_empty"
  CHECK ("content" IS NULL OR length(trim("content")) > 0);

CREATE INDEX IF NOT EXISTS "ix_messages_conversation_id_sent_at_id"
  ON "messages" ("conversation_id", "sent_at" DESC, "id" DESC);

CREATE INDEX IF NOT EXISTS "ix_messages_sender_user_id"
  ON "messages" ("sender_user_id");

CREATE TABLE IF NOT EXISTS "message_attachments" (
  -- primary key
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- table fields
  "message_id" INTEGER NOT NULL,
  "type" VARCHAR(20) NOT NULL,
  "url" VARCHAR(2048) NOT NULL,
  "original_file_name" VARCHAR(255),
  "content_type" VARCHAR(100) NOT NULL,
  "size_bytes" BIGINT NOT NULL,
  "width" INTEGER,
  "height" INTEGER,
  "sort_order" SMALLINT DEFAULT 0 NOT NULL,
  -- common fields
  "entity_id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "updated_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "is_deleted" BOOLEAN DEFAULT false NOT NULL,
  -- constraints
  CONSTRAINT "fk_message_attachments_messages_message_id" FOREIGN KEY ("message_id") REFERENCES "messages"("id") ON DELETE CASCADE,
  CONSTRAINT "ck_message_attachments_type" CHECK ("type" IN ('image')),
  CONSTRAINT "ck_message_attachments_url_not_empty" CHECK (length(trim("url")) > 0),
  CONSTRAINT "ck_message_attachments_content_type_not_empty" CHECK (length(trim("content_type")) > 0),
  CONSTRAINT "ck_message_attachments_size_bytes_positive" CHECK ("size_bytes" > 0),
  CONSTRAINT "ck_message_attachments_width_positive" CHECK ("width" IS NULL OR "width" > 0),
  CONSTRAINT "ck_message_attachments_height_positive" CHECK ("height" IS NULL OR "height" > 0),
  CONSTRAINT "ck_message_attachments_sort_order_non_negative" CHECK ("sort_order" >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS "ux_message_attachments_entity_id"
  ON "message_attachments" ("entity_id");

CREATE UNIQUE INDEX IF NOT EXISTS "ux_message_attachments_message_id_sort_order"
  ON "message_attachments" ("message_id", "sort_order")
  WHERE "is_deleted" = false;

CREATE INDEX IF NOT EXISTS "ix_message_attachments_message_id"
  ON "message_attachments" ("message_id");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_conversations_messages_last_message_id'
  ) THEN
    ALTER TABLE "conversations"
      ADD CONSTRAINT "fk_conversations_messages_last_message_id"
      FOREIGN KEY ("last_message_id") REFERENCES "messages"("id") ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_conversation_members_messages_last_read_message_id'
  ) THEN
    ALTER TABLE "conversation_members"
      ADD CONSTRAINT "fk_conversation_members_messages_last_read_message_id"
      FOREIGN KEY ("last_read_message_id") REFERENCES "messages"("id") ON DELETE SET NULL;
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS "friend_requests" (
  -- primary key
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- table fields
  "requester_user_id" INTEGER NOT NULL,
  "addressee_user_id" INTEGER NOT NULL,
  "user_low_id" INTEGER GENERATED ALWAYS AS (LEAST("requester_user_id", "addressee_user_id")) STORED,
  "user_high_id" INTEGER GENERATED ALWAYS AS (GREATEST("requester_user_id", "addressee_user_id")) STORED,
  "status" VARCHAR(20) DEFAULT 'pending' NOT NULL,
  "responded_at" TIMESTAMPTZ,
  -- common fields
  "entity_id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "updated_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "is_deleted" BOOLEAN DEFAULT false NOT NULL,
  -- constraints
  CONSTRAINT "fk_friend_requests_users_requester_user_id" FOREIGN KEY ("requester_user_id") REFERENCES "users"("id") ON DELETE CASCADE,
  CONSTRAINT "fk_friend_requests_users_addressee_user_id" FOREIGN KEY ("addressee_user_id") REFERENCES "users"("id") ON DELETE CASCADE,
  CONSTRAINT "ck_friend_requests_different_users" CHECK ("requester_user_id" <> "addressee_user_id"),
  CONSTRAINT "ck_friend_requests_status" CHECK ("status" IN ('pending', 'accepted', 'declined', 'canceled'))
);

CREATE UNIQUE INDEX IF NOT EXISTS "ux_friend_requests_entity_id"
  ON "friend_requests" ("entity_id");

DROP INDEX IF EXISTS "ux_friend_requests_pending_user_pair";

ALTER TABLE "friend_requests"
  ADD COLUMN IF NOT EXISTS "user_low_id" INTEGER GENERATED ALWAYS AS (LEAST("requester_user_id", "addressee_user_id")) STORED;

ALTER TABLE "friend_requests"
  ADD COLUMN IF NOT EXISTS "user_high_id" INTEGER GENERATED ALWAYS AS (GREATEST("requester_user_id", "addressee_user_id")) STORED;

CREATE UNIQUE INDEX IF NOT EXISTS "ux_friend_requests_pending_user_pair"
  ON "friend_requests" ("user_low_id", "user_high_id")
  WHERE "status" = 'pending' AND "is_deleted" = false;

CREATE INDEX IF NOT EXISTS "ix_friend_requests_requester_user_id"
  ON "friend_requests" ("requester_user_id");

CREATE INDEX IF NOT EXISTS "ix_friend_requests_addressee_user_id"
  ON "friend_requests" ("addressee_user_id");

CREATE TABLE IF NOT EXISTS "friendships" (
  -- primary key
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- table fields
  "user_low_id" INTEGER NOT NULL,
  "user_high_id" INTEGER NOT NULL,
  "accepted_request_id" INTEGER,
  -- common fields
  "entity_id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "updated_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "is_deleted" BOOLEAN DEFAULT false NOT NULL,
  -- constraints
  CONSTRAINT "fk_friendships_users_user_low_id" FOREIGN KEY ("user_low_id") REFERENCES "users"("id") ON DELETE CASCADE,
  CONSTRAINT "fk_friendships_users_user_high_id" FOREIGN KEY ("user_high_id") REFERENCES "users"("id") ON DELETE CASCADE,
  CONSTRAINT "fk_friendships_friend_requests_accepted_request_id" FOREIGN KEY ("accepted_request_id") REFERENCES "friend_requests"("id") ON DELETE SET NULL,
  CONSTRAINT "ck_friendships_different_users" CHECK ("user_low_id" < "user_high_id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "ux_friendships_entity_id"
  ON "friendships" ("entity_id");

CREATE UNIQUE INDEX IF NOT EXISTS "ux_friendships_user_pair"
  ON "friendships" ("user_low_id", "user_high_id")
  WHERE "is_deleted" = false;

CREATE INDEX IF NOT EXISTS "ix_friendships_user_low_id"
  ON "friendships" ("user_low_id");

CREATE INDEX IF NOT EXISTS "ix_friendships_user_high_id"
  ON "friendships" ("user_high_id");
