CREATE TABLE IF NOT EXISTS "users" (
  -- primary key
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- table fields
  "username" VARCHAR(20) NOT NULL,
  "email" VARCHAR(50) NOT NULL,
  "password_hash" VARCHAR NOT NULL,
  "full_name" varchar(100),
  "avatar_url" VARCHAR,
  "is_email_verified" BOOLEAN DEFAULT false NOT NULL,
  "last_sign_in_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  -- common fields
  "entity_id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "updated_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "is_deleted" BOOLEAN DEFAULT false NOT NULL
  -- constraints
);

CREATE TABLE IF NOT EXISTS "refresh_tokens" (
  -- primary key
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- table fiedls
  "user_id" INTEGER NOT NULL,
  "token" VARCHAR NOT NULL,
  "is_revoked" BOOLEAN DEFAULT false NOT NULL,
  "expires_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "replaced_by_token" VARCHAR,
  -- commnon fields
  "entity_id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "updated_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  "is_deleted" BOOLEAN DEFAULT false NOT NULL,
  -- constraints
  CONSTRAINT "fk_refresh_token_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
);
