/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as PublicHelpIndexRouteImport } from './routes/_public/help/index'
import { Route as GuestSignUpIndexRouteImport } from './routes/_guest/sign-up/index'
import { Route as GuestSignInIndexRouteImport } from './routes/_guest/sign-in/index'
import { Route as AuthenticatedThreadsThreadIdIndexRouteImport } from './routes/_authenticated/threads/$threadId/index'
import { Route as AuthenticatedSettingsUsernameIndexRouteImport } from './routes/_authenticated/settings/$username/index'
import { Route as AuthenticatedProfileUsernameIndexRouteImport } from './routes/_authenticated/profile/$username/index'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicHelpIndexRoute = PublicHelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => PublicRoute,
} as any)
const GuestSignUpIndexRoute = GuestSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => GuestRoute,
} as any)
const GuestSignInIndexRoute = GuestSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => GuestRoute,
} as any)
const AuthenticatedThreadsThreadIdIndexRoute =
  AuthenticatedThreadsThreadIdIndexRouteImport.update({
    id: '/threads/$threadId/',
    path: '/threads/$threadId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsUsernameIndexRoute =
  AuthenticatedSettingsUsernameIndexRouteImport.update({
    id: '/settings/$username/',
    path: '/settings/$username/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileUsernameIndexRoute =
  AuthenticatedProfileUsernameIndexRouteImport.update({
    id: '/profile/$username/',
    path: '/profile/$username/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in/': typeof GuestSignInIndexRoute
  '/sign-up/': typeof GuestSignUpIndexRoute
  '/help/': typeof PublicHelpIndexRoute
  '/profile/$username/': typeof AuthenticatedProfileUsernameIndexRoute
  '/settings/$username/': typeof AuthenticatedSettingsUsernameIndexRoute
  '/threads/$threadId/': typeof AuthenticatedThreadsThreadIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof GuestSignInIndexRoute
  '/sign-up': typeof GuestSignUpIndexRoute
  '/help': typeof PublicHelpIndexRoute
  '/profile/$username': typeof AuthenticatedProfileUsernameIndexRoute
  '/settings/$username': typeof AuthenticatedSettingsUsernameIndexRoute
  '/threads/$threadId': typeof AuthenticatedThreadsThreadIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_guest/sign-in/': typeof GuestSignInIndexRoute
  '/_guest/sign-up/': typeof GuestSignUpIndexRoute
  '/_public/help/': typeof PublicHelpIndexRoute
  '/_authenticated/profile/$username/': typeof AuthenticatedProfileUsernameIndexRoute
  '/_authenticated/settings/$username/': typeof AuthenticatedSettingsUsernameIndexRoute
  '/_authenticated/threads/$threadId/': typeof AuthenticatedThreadsThreadIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in/'
    | '/sign-up/'
    | '/help/'
    | '/profile/$username/'
    | '/settings/$username/'
    | '/threads/$threadId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/help'
    | '/profile/$username'
    | '/settings/$username'
    | '/threads/$threadId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_guest'
    | '/_public'
    | '/_authenticated/'
    | '/_guest/sign-in/'
    | '/_guest/sign-up/'
    | '/_public/help/'
    | '/_authenticated/profile/$username/'
    | '/_authenticated/settings/$username/'
    | '/_authenticated/threads/$threadId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/help/': {
      id: '/_public/help/'
      path: '/help'
      fullPath: '/help/'
      preLoaderRoute: typeof PublicHelpIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_guest/sign-up/': {
      id: '/_guest/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof GuestSignUpIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/sign-in/': {
      id: '/_guest/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof GuestSignInIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_authenticated/threads/$threadId/': {
      id: '/_authenticated/threads/$threadId/'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId/'
      preLoaderRoute: typeof AuthenticatedThreadsThreadIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/$username/': {
      id: '/_authenticated/settings/$username/'
      path: '/settings/$username'
      fullPath: '/settings/$username/'
      preLoaderRoute: typeof AuthenticatedSettingsUsernameIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/$username/': {
      id: '/_authenticated/profile/$username/'
      path: '/profile/$username'
      fullPath: '/profile/$username/'
      preLoaderRoute: typeof AuthenticatedProfileUsernameIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProfileUsernameIndexRoute: typeof AuthenticatedProfileUsernameIndexRoute
  AuthenticatedSettingsUsernameIndexRoute: typeof AuthenticatedSettingsUsernameIndexRoute
  AuthenticatedThreadsThreadIdIndexRoute: typeof AuthenticatedThreadsThreadIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProfileUsernameIndexRoute:
    AuthenticatedProfileUsernameIndexRoute,
  AuthenticatedSettingsUsernameIndexRoute:
    AuthenticatedSettingsUsernameIndexRoute,
  AuthenticatedThreadsThreadIdIndexRoute:
    AuthenticatedThreadsThreadIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface GuestRouteChildren {
  GuestSignInIndexRoute: typeof GuestSignInIndexRoute
  GuestSignUpIndexRoute: typeof GuestSignUpIndexRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestSignInIndexRoute: GuestSignInIndexRoute,
  GuestSignUpIndexRoute: GuestSignUpIndexRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

interface PublicRouteChildren {
  PublicHelpIndexRoute: typeof PublicHelpIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicHelpIndexRoute: PublicHelpIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
